# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 464c631178f0ce8227929a230192e0673fb3480d4841181893742bcace09d76e482f0fcd2a9ade4b5a0e1dd67d931d9b77221e00d77a7116b078b8a863ac9a7d

test:
  secret_key_base: a571037ace98506bd0d896ba7c91a725cef38468761dc1f7e09026907193acd503f053de0eedfa30576733bf720ae2b7c1ce9b7e435594405953979f31558626

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
